version: '3.8'

services:
  api:
    build: .
    container_name: jmmi-be
    restart: always
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=production
      - PORT=3333
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/jmmi_db?schema=public
    depends_on:
      - db
    networks:
      - jmmi-network

  db:
    image: postgres:15-alpine
    container_name: jmmi-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jmmi_db
    ports:
      - "5454:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - jmmi-network

volumes:
  pgdata:

networks:
  jmmi-network:
